sudo: true
language: python
python:
  - "3.6"
before_install:
  - chmod +x ./bin/*.sh
  - "pip install pipenv"
install:
  - "./bin/prepare.sh"
script:
  - echo "[ci] running tests against $(pipenv run python --version) ..."
  - "./bin/run.sh"
jobs:
  include:
    - stage: deploy
      python: 3.6
      script:
        - echo "[ci] deploying to pypi..."
        - "./bin/release.sh"
branches:
  only:
    - master
deploy:
  provider: pypi
  user: daniloster
  password:
    secure: YVWwDTHyDZnyaAKpWWo3aYPNpeotc3SyHFqBC3gnZ5A8jfiQlOdWj4yr+SnJaMPW6eTu+BbHrJ4ymSifMxsRKyhpbLTMBa3g8QeqNXAMqFUNph5R8xFBC2hTEFpOE6lTUyjU6lzlhusE8nRdYZiGol8l3jHymVKTPcOeECO3OPanRDMl3/gtn9BPQ7BI8kpqMRZh+ssRaT7+6WgLtRVvirRjI4XObKQDX24BFBc+r3mxqsdTF1t+YpjbRm/llWYoEM/kJ4VyHIfI4rykj9dxbglR71DVKKMtPgH3XObLY/MnLS0xzKuxdA6q9xV1JcZOqADyGFPWwcyYMk6pqzjbnGV8pUmvnQrQjJVQhY+krtAuT9rRt+Nqvp2UngUb7VG7fBGVtM7cMlYQLvavqNuNtH385tcdVj64LT1X6lXU5DdI8EW2ySvYOdJLi67Z6QnoSTtjelZpoeRzv5sfSfUX0zWL75nMMrsj5dPebDfJfUgg5KQghVOBcobnsfATbf/xaAnGYMVr6uFdCHO51Th13m8PPDJ2yIzrXfZtECmwRkXuKrbWsgwsTOyoLpOoy1J2cllvHLMeJBOxxOEwLyZ+KyVwLHMz94+hvZkMzuDRA7eXZflspElLBvXPzL3mePijEmDYN9u+zS+S55aOdOi+tx9ET9yYYtXDCehoUIuNmxA=
  skip_existing: true
  skip_cleanup: true
  on:
    branch: master
after_deploy:
  - "./bin/after_release.sh"

env:
  global:
    secure: dW9P63NQjWGdhfBsnzGXSC24zn16Vp3bI1JHezZ3ylD1ngixh14ikORdEt9WvJaol4n55C7FidS3yGCUDrdKyxZil+Rqdt1qtOJ5cpKwiqIPfPs1GdlelS/zD2NEqAM/AAxfiKWbAbqNMme+f/0H/HV7lYlbRIH0Uj/GUCvUu7hk8Fand2JeetCBhMs9pcNkmAEMrvMLdFloABtbDYqubmHB2Q+j8KiiYDVX8GE+HRhRnQCcIkZa82/QvDDcWLDdDbor+xw2sUmqJzabwVEyj+61Qp7coWnvT3Yt9dqvHznyPnVPrxUn1w0ZiO/2PuE1Z98kpKVADkNBqfg5jOq7qG+V9/pf/DCB7nq6zmFZJs8nQRap9ePnETChLuXcYuKLbSUCrDDvT/0hVMBD7dPcWN3oLuiHw6JmazxHuojq6ZX+J1aVuOsrbqg0+7H3kizsmAUQSJhY+eOKz6R0G8Flfkr6M3+4j19yZlbF+nzBGjgP20wdRXlIMDcemS54kLuYE77p+yFn3RPH9IrVmWXXyh2pahWcl+VFMM2Yt6MjMc9bXpFSBin3hfKTP0j0VuUgo8TnMh2cL8+p3cCpAXTIrKrb5MArYARB8v0++EKKS13JPiC0rzQh7uRy37wT3SDnZ95CyUQ48uEe2xPc2JoDLK8qogI+rYgXlXen2NokygI=
